# Generated by Django 4.2.26 on 2025-12-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='attachment',
        ),
    ]
